name: Python package

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Poetry
        shell: pwsh
        run: pipx install poetry

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Setup Environment Variables
        shell: pwsh
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "NUITKA_CACHE_DIR=${{ github.action_path }}/nuitka/cache"
          $pythonVersion = (python --version 2>&1).Split(' ')[1] -replace '\.(\d+)$', '.$1'
          Add-Content -Path $env:GITHUB_ENV -Value "PYTHON_VERSION=$pythonVersion"

      - name: Cache Nuitka cache directory
        uses: actions/cache@v4
        with:
          path: ${{ env.NUITKA_CACHE_DIR }}
          key: ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-nuitka-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-python-${{ env.PYTHON_VERSION }}-
            ${{ runner.os }}-python-
            ${{ runner.os }}-

      - name: Install dependencies
        shell: pwsh
        run: poetry install

      - name: Build package
        shell: pwsh
        run: poetry run python build.py

      - name: Upload release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true
          files: build/*.exe
